[package]
name = "trybuild"
version = "0.0.0"
edition = "2021"

[dependencies]
basic-toml = "0.1.8"
dissimilar = { version = "1.0"}
glob = "0.3"
once_cell = "1.9"
serde = "1.0.194"
serde_derive = "1.0.194"
serde_json = "1.0.110"
termcolor = "1.0.4"

driver = { path = "../../driver" }
